name: satellite-data
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=20.3.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - cartopy=0.18.0
  - certifi=2020.12.5
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - curl=7.75.0
  - cycler=0.10.0
  - decorator=4.4.2
  - ecos=2.0.7.post1
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - fontconfig=2.13.1
  - freeglut=3.2.1
  - freetype=2.10.4
  - freexl=1.0.6
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=68.1
  - intel-openmp=2020.3
  - jasper=2.0.14
  - jdcal=1.4.1
  - joblib=1.0.1
  - jpeg=9d
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.75.0
  - libffi=3.3
  - libgdal=3.1.4
  - libglib=2.68.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.7.4
  - libopencv=4.5.1
  - libpng=1.6.37
  - libpq=13.1
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2020.4
  - msys2-conda-epoch=20160418
  - networkx=2.5
  - numpy=1.20.1
  - opencv=4.5.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pillow=8.1.2
  - pip=21.0.1
  - proj=7.2.0
  - py-opencv=4.5.1
  - pyparsing=2.4.7
  - pyproj=3.0.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyshp=2.1.3
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - rarfile=4.0
  - rasterio=1.2.1
  - scipy=1.6.1
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snuggs=1.4.7
  - tabulate=0.8.9
  - threadpoolctl=2.1.0
  - tiledb=2.2.6
  - tk=8.6.10
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - wincertstore=0.2
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - jupyter
  - patool
  - pyresample
